/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sona.gui;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import com.sona.operations.LogInProcess;
import com.sona.themes.mac;
import java.awt.event.KeyEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import raven.toast.Notifications;

/**
 *
 * @author Sampath
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Notifications.getInstance().setJFrame(this);
    }

    public static boolean verifyEmail(String email) {
        if (email == null || email.isEmpty()) {
            return false; // Email is empty or null
        }

        // Regular expression for basic email validation
        String emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";
        Pattern pattern = Pattern.compile(emailRegex);
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }

    public static boolean verifyPassword(String password) {
        if (password == null || password.isEmpty()) {
            return false; // Password is empty or null
        }

        // Password requirements:
        // - At least 8 characters long
        // - Contains at least one uppercase letter
        // - Contains at least one lowercase letter
        // - Contains at least one digit
        // - Contains at least one special character
        String passwordRegex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$";

        Pattern pattern = Pattern.compile(passwordRegex);
        Matcher matcher = pattern.matcher(password);
        return matcher.matches();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        passInput = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        loginTitle = new javax.swing.JLabel();
        usernameInput = new javax.swing.JTextField();
        login1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Authenication");
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(20, 20, 20));
        setMinimumSize(new java.awt.Dimension(500, 300));
        setPreferredSize(new java.awt.Dimension(500, 250));
        setSize(new java.awt.Dimension(300, 100));
        setType(java.awt.Window.Type.POPUP);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setMinimumSize(new java.awt.Dimension(1000, 123));
        mainPanel.setLayout(new java.awt.GridBagLayout());

        username.setForeground(new java.awt.Color(0, 153, 153));
        username.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 10, 20);
        mainPanel.add(username, gridBagConstraints);

        pass.setForeground(new java.awt.Color(0, 153, 153));
        pass.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 20);
        mainPanel.add(pass, gridBagConstraints);

        passInput.setMinimumSize(new java.awt.Dimension(400, 40));
        passInput.setPreferredSize(new java.awt.Dimension(64, 45));
        passInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passInputKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passInputKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        mainPanel.add(passInput, gridBagConstraints);

        login.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        login.setForeground(new java.awt.Color(0, 102, 102));
        login.setText("Submit");
        login.setMinimumSize(new java.awt.Dimension(90, 35));
        login.setPreferredSize(new java.awt.Dimension(100, 45));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 15, 30);
        mainPanel.add(login, gridBagConstraints);

        loginTitle.setBackground(new java.awt.Color(255, 255, 255));
        loginTitle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        loginTitle.setForeground(new java.awt.Color(0, 153, 153));
        loginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginTitle.setText("Hello");
        loginTitle.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 20, 30);
        mainPanel.add(loginTitle, gridBagConstraints);

        usernameInput.setMinimumSize(new java.awt.Dimension(64, 40));
        usernameInput.setPreferredSize(new java.awt.Dimension(64, 45));
        usernameInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameInputKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernameInputKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 20);
        mainPanel.add(usernameInput, gridBagConstraints);

        login1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        login1.setForeground(new java.awt.Color(0, 102, 102));
        login1.setText("Passwod Reset");
        login1.setMinimumSize(new java.awt.Dimension(150, 25));
        login1.setPreferredSize(new java.awt.Dimension(150, 25));
        login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 15, 30);
        mainPanel.add(login1, gridBagConstraints);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameInputKeyReleased
        // TODO add your handling code here:
        var Text = usernameInput.getText();
        if (0 < Text.length()) {
            username.setText("");
        } else {
            username.setText("Username");
        }
    }//GEN-LAST:event_usernameInputKeyReleased

    private void passInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passInputKeyReleased
        // TODO add your handling code here:
        char[] Text = passInput.getPassword();
        if (0 < Text.length) {
            pass.setText("");
        } else {
            pass.setText("Password");
        }
    }//GEN-LAST:event_passInputKeyReleased

    private void usernameInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameInputKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (usernameInput.getText().isEmpty() || passInput.getPassword().length == 0) {
                JOptionPane.showMessageDialog(this, "Please Fill Both Fields!", "Warning!", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_usernameInputKeyPressed

    private void passInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passInputKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (usernameInput.getText().isEmpty() || passInput.getPassword().length == 0) {
                JOptionPane.showMessageDialog(this, "Please Fill Both Fields!", "Warning!", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_passInputKeyPressed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        if (usernameInput.getText().isEmpty() || passInput.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Please Fill Both Fields!", "Warning!", JOptionPane.WARNING_MESSAGE);
        } else {
            LogInProcess LProcess = new LogInProcess();
            LProcess.handleLogin(this, usernameInput, passInput);
        }
    }//GEN-LAST:event_loginActionPerformed

    private void login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login1ActionPerformed
        // TODO add your handling code here:

        this.setFocusable(false);
        this.setAlwaysOnTop(false);
        new ForgotPass().setVisible(true);
    }//GEN-LAST:event_login1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        FlatLaf.registerCustomDefaultsSource( "com.sona.themes" );
        mac.setup();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton login;
    private javax.swing.JButton login1;
    private javax.swing.JLabel loginTitle;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel pass;
    private javax.swing.JPasswordField passInput;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usernameInput;
    // End of variables declaration//GEN-END:variables
}
